# KEEP. This script is still the source of the object(s) it writes.
#
#   METABOLOMICS_CVS
#
# Builds the metabolite coefficient-of-variation table. precovid-repro stages its copy from the production bucket's metabolite-cv tier, which is why the shipped object can be newer than what this script last produced.
#
# precovid-repro STAGES these rather than rebuilding them — its Stage 1 copies
# the object through verbatim, so the pipeline is a carrier here, not a
# producer. inst/PROVENANCE.tsv records them as `staged-verbatim` rather than
# `regenerated`, and that is the distinction: a regenerated object has its
# generator in precovid-repro and this repo's copy was retired; a staged one
# has its generator HERE and nowhere else. Retiring this file would leave the
# object with no way to be rebuilt at all.

#this was generated by the metabolomics analysts: David JM, Gayatri Iyer. please refer to them for questions about metabolomics CVs
library(dplyr)
tissue_mapping = MotrpacHumanPreSuspensionAnalysis::OME_TISSUE_CODE %>%
  select(-ome) %>%
  dplyr::distinct(tissue_code, .keep_all = T)
config = jsonlite::fromJSON("~/config.json")
#basically wherever you want to downloads stuff to.
repo_local_dir = config$precovid_repo_path

metab_file_path = "gs://motrpac-data-hub/analysis/human-precovid-sed-adu/v1.3/resources/motrpac_human-precovid_metabolite-cv_v1.2.txt"
METABOLOMICS_CVS = MotrpacBicQC::dl_read_gcp(path = metab_file_path,
                                      tmpdir = file.path(repo_local_dir, "data", "tmp"))

usethis::use_data(METABOLOMICS_CVS, overwrite = TRUE)
